### ISSUE TITLE
Keep letter case provided by user

### ISSUE THREAD

**Issue by wjglerum** [lunatech-labs/lunatech-tech-matrix#116]
Some technologies have specific ways of casing their names. Currently the app ignores all casing provided by the user and changed to use upper case for the first letter and lower case for the others.

For example `DC/OS` becomes `Dc/Os` which looks weird to me.

**Comment by pedrolunatech** [comment]
For this we need to add a new field to be used as label for front end purposes while name continues to act as unique identifier.
