### ISSUE TITLE
Add level for DM report

### ISSUE THREAD

**Issue by mahyaa** [lunatech-labs/lunatech-tech-matrix#129]
In DM report we have fields for `Tech`, `Action`, and `Occurrence`. 
New fields is needed to show the level of the technology in the report.
In case some one update their level, we can show the last two levels they had. Or there can be a separate report to keep log for level changes.

**Comment by pedrolunatech** [comment]
Added on https://github.com/lunatech-labs/lunatech-tech-matrix/pull/136/commits/5e43000f4bb2d7d941b967ff82532d010fb99d34
